### ISSUE TITLE
sed issues with linebreak on macOS

### ISSUE THREAD

**Issue by geoalchimista** [dudektria/doi2bib#1]
Hi,

Nice tool!

I found some issues with the `sed` commands in lines 76--78 of the script. 
```bash
    sed -e 's/^ *//' \
        -e 's/, /,\n /g' \
        -e 's/}}$/}\n}\n/'
```
I'm running a macOS High Sierra, so it's probably caused by the subtle differences between the macOS (BSD) `sed` and GNU `sed`. I found a simple fix to it—using `$'string'` and replace `\n` with `\\\n`.

Then I found that the script would insert a linebreak at every comma, and this would also apply to the `author` field, which I suppose is not an intended feature. So I changed it to match `','` only for the first occurrence (basically, the one after the BiBTeX Key field). And `'}, '` is then used for inserting a linebreak after each field.

With these changes, I think it will work under both macOS and GNU/Linux (I tested it with `gnu-sed`).
```bash
    sed -e $'s/^ *//' \
        -e $'s/}, /},\\\n  /g' \
        -e $'s/, /,\\\n  /1' \
        -e $'s/}}$/}\\\n}\\\n/'
 ```

**Comment by schneiderfelipe** [comment]
Great! I tested your code and it also works fine on my Ubuntu.
I added your contribution to the last version of the script. Thanks!
